version: '2'
services:
    test-app:
        image: test
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=test-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    test-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: test-cassandra
    test-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=test-cassandra
    test-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: test-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
